server:
  port: 8500
  servlet:
    context-path: /product-service

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

resilience4j:
  circuitbreaker:
    instances:
      productService:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
        sliding-window-size: 10

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
